version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - database
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=linkedin-db
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - linkedin-db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

networks:
  backend:
    driver: bridge

volumes:
  linkedin-db-data:
